# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AroCodes.AroCrypt
PackageVersion: 0.7.0
InstallerType: nullsoft
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/OfficialAroCodes/AroCrypt/releases/download/v0.7.0/AroCrypt-Setup-0.7.0.exe
  InstallerSha256: 9406962291BAB4C7AACF27D95AF389E2B284960DFB4B4D5005FDA5E9616CF6A7
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-06-26
